wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.12.2
    cli_version: 0.16.6
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1712632825.0
    t:
      1:
      - 1
      - 5
      - 35
      - 41
      - 49
      - 53
      - 55
      - 63
      - 66
      - 71
      2:
      - 1
      - 5
      - 35
      - 41
      - 49
      - 53
      - 55
      - 63
      - 66
      - 71
      3:
      - 13
      - 23
      - 61
      4: 3.12.2
      5: 0.16.6
      8:
      - 5
      13: darwin-x86_64
composer_version:
  desc: null
  value: 0.21.2
composer_commit_hash:
  desc: null
  value: None
num_nodes:
  desc: null
  value: 1
num_mpss_per_node:
  desc: null
  value: 1
node_name:
  desc: null
  value: unknown because NODENAME environment variable not set
rank_zero_seed:
  desc: null
  value: 1
