wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.12.2
    cli_version: 0.16.6
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1712632218.0
    t:
      1:
      - 1
      - 5
      - 35
      - 41
      - 49
      - 53
      - 55
      - 63
      - 66
      - 71
      2:
      - 1
      - 5
      - 35
      - 41
      - 49
      - 53
      - 55
      - 63
      - 66
      - 71
      3:
      - 13
      - 23
      4: 3.12.2
      5: 0.16.6
      8:
      - 5
      13: darwin-x86_64
